import Head from 'next/head'
import NavBar from '../NavBar'
import styles from './MainLayout.module.css'

type MainLayoutProps = {
  children: JSX.Element | JSX.Element[]
}

export default function MainLayout({ children }: MainLayoutProps) {
  return (
    <>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NavBar />
      <main className={styles.main}>
      { children }
      </main>
    </>
  )
}